# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SSDcalculate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import re

from PyQt5 import QtCore, QtGui, QtWidgets

from Alignment import Ui_Alignment
from helper import Helper


class Ui_SsdCalculator(object):
    def __init__(self, SsdCalculator):
        self.SsdCalculator = SsdCalculator

        self.template = []
        self.target = []
        self.template_sequence = ''
        self.target_sequence = ''
        self.target_number = []  # list of tuples like ('TM1 start', 'TM1 end'), ('TM2 start', 'TM2 end'), ...
        self.template_number = []  # list of tuples like ('TM1 start', 'TM1 end'), ('TM2 start', 'TM2 end'), ...
        self.alignment = []

        self.ress = []
        self.hydrh = []
        self.summ = [0] * 7
        self.value = [0] * 7
        self.name = ''

    def setup_ui(self):
        self.SsdCalculator.setObjectName("SsdCalculator")
        self.SsdCalculator.resize(954, 959)
        self.central_widget = QtWidgets.QWidget(self.SsdCalculator)
        self.central_widget.setObjectName("central_widget")

        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setGeometry(QtCore.QRect(690, 50, 59, 15))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.ssd_TM1 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM1.setGeometry(QtCore.QRect(680, 100, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM1.setFont(font)
        self.ssd_TM1.setObjectName("ssd_TM1")

        self.ssd_TM2 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM2.setGeometry(QtCore.QRect(680, 150, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM2.setFont(font)
        self.ssd_TM2.setObjectName("ssd_TM2")

        self.ssd_TM3 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM3.setGeometry(QtCore.QRect(680, 200, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM3.setFont(font)
        self.ssd_TM3.setObjectName("ssd_TM3")

        self.ssd_TM4 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM4.setGeometry(QtCore.QRect(680, 250, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM4.setFont(font)
        self.ssd_TM4.setObjectName("ssd_TM4")

        self.ssd_TM5 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM5.setGeometry(QtCore.QRect(680, 300, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM5.setFont(font)
        self.ssd_TM5.setObjectName("ssd_TM5")

        self.ssd_TM6 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM6.setGeometry(QtCore.QRect(680, 350, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM6.setFont(font)
        self.ssd_TM6.setObjectName("ssd_TM6")

        self.ssd_TM7 = QtWidgets.QLabel(self.central_widget)
        self.ssd_TM7.setGeometry(QtCore.QRect(680, 400, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ssd_TM7.setFont(font)
        self.ssd_TM7.setObjectName("ssd_TM7")

        self.calculate_button = QtWidgets.QPushButton(self.central_widget)
        self.calculate_button.setGeometry(QtCore.QRect(700, 600, 190, 31))
        self.calculate_button.setObjectName("calculate")
        self.calculate_button.clicked.connect(self.calculate)

        self.show_alignment_button = QtWidgets.QPushButton(self.central_widget)
        self.show_alignment_button.setGeometry(QtCore.QRect(700, 650, 190, 31))
        self.show_alignment_button.setObjectName("show_alignment_button")
        self.show_alignment_button.clicked.connect(self.show_alignment_click_handler)

        self.show_hydrophobicity_plot_button = QtWidgets.QPushButton(self.central_widget)
        self.show_hydrophobicity_plot_button.setGeometry(QtCore.QRect(700, 700, 190, 31))
        self.show_hydrophobicity_plot_button.setObjectName("show_hydrophobicity_plot_button")
        self.show_hydrophobicity_plot_button.clicked.connect(self.show_hydrophobicity_plot)

        self.show_helical_plot_button = QtWidgets.QPushButton(self.central_widget)
        self.show_helical_plot_button.setGeometry(QtCore.QRect(700, 750, 190, 31))
        self.show_helical_plot_button.setObjectName("show_helical_plot_button")
        self.show_helical_plot_button.clicked.connect(self.show_helical_plot)

        self.download_result_summary_button = QtWidgets.QPushButton(self.central_widget)
        self.download_result_summary_button.setGeometry(QtCore.QRect(700, 800, 190, 31))
        self.download_result_summary_button.setObjectName("download_result_summary_button")
        self.download_result_summary_button.clicked.connect(self.download_result_summary)

        self.label_3 = QtWidgets.QLabel(self.central_widget)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 581, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.label_5 = QtWidgets.QLabel(self.central_widget)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.home_button = QtWidgets.QPushButton(self.central_widget)
        self.home_button.setGeometry(QtCore.QRect(810, 10, 80, 23))
        self.home_button.setObjectName("home_button")
        self.home_button.clicked.connect(self.back_home)

        self.clear_button = QtWidgets.QPushButton(self.central_widget)
        self.clear_button.setGeometry(QtCore.QRect(720, 10, 80, 23))
        self.clear_button.setObjectName("clear_button")
        self.clear_button.clicked.connect(self.clear_button_handler)

        self.example_input_button = QtWidgets.QPushButton(self.central_widget)
        self.example_input_button.setGeometry(QtCore.QRect(599, 10, 111, 23))
        self.example_input_button.setObjectName("example_input_button")
        self.example_input_button.clicked.connect(self.example_button_handler)

        self.label_6 = QtWidgets.QLabel(self.central_widget)
        self.label_6.setGeometry(QtCore.QRect(20, 480, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.template_sequence_field = QtWidgets.QTextEdit(self.central_widget)
        self.template_sequence_field.setGeometry(QtCore.QRect(20, 90, 550, 140))
        self.template_sequence_field.setObjectName("template_sequence")
        self.template_sequence_field.textChanged.connect(self.on_text_changed)

        self.target_sequence_field = QtWidgets.QTextEdit(self.central_widget)
        self.target_sequence_field.setGeometry(QtCore.QRect(20, 510, 550, 140))
        self.target_sequence_field.setObjectName("target_sequence")
        self.target_sequence_field.textChanged.connect(self.on_text_changed)

        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setGeometry(QtCore.QRect(20, 250, 59, 15))
        self.label.setObjectName("label")

        self.label_4 = QtWidgets.QLabel(self.central_widget)
        self.label_4.setGeometry(QtCore.QRect(20, 280, 59, 15))
        self.label_4.setObjectName("label_4")

        self.label_7 = QtWidgets.QLabel(self.central_widget)
        self.label_7.setGeometry(QtCore.QRect(180, 250, 59, 15))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.central_widget)
        self.label_8.setGeometry(QtCore.QRect(180, 280, 59, 15))
        self.label_8.setObjectName("label_8")

        self.label_9 = QtWidgets.QLabel(self.central_widget)
        self.label_9.setGeometry(QtCore.QRect(20, 310, 81, 16))
        self.label_9.setObjectName("label_9")

        self.label_11 = QtWidgets.QLabel(self.central_widget)
        self.label_11.setGeometry(QtCore.QRect(330, 250, 59, 15))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.central_widget)
        self.label_12.setGeometry(QtCore.QRect(330, 280, 59, 15))
        self.label_12.setObjectName("label_12")

        self.label_14 = QtWidgets.QLabel(self.central_widget)
        self.label_14.setGeometry(QtCore.QRect(470, 250, 59, 15))
        self.label_14.setObjectName("label_14")

        self.label_15 = QtWidgets.QLabel(self.central_widget)
        self.label_15.setGeometry(QtCore.QRect(470, 280, 59, 15))
        self.label_15.setObjectName("label_15")

        self.label_17 = QtWidgets.QLabel(self.central_widget)
        self.label_17.setGeometry(QtCore.QRect(20, 370, 59, 15))
        self.label_17.setObjectName("label_17")

        self.label_18 = QtWidgets.QLabel(self.central_widget)
        self.label_18.setGeometry(QtCore.QRect(20, 400, 59, 15))
        self.label_18.setObjectName("label_18")

        self.label_20 = QtWidgets.QLabel(self.central_widget)
        self.label_20.setGeometry(QtCore.QRect(180, 370, 59, 15))
        self.label_20.setObjectName("label_20")

        self.label_21 = QtWidgets.QLabel(self.central_widget)
        self.label_21.setGeometry(QtCore.QRect(180, 400, 59, 15))
        self.label_21.setObjectName("label_21")

        self.label_23 = QtWidgets.QLabel(self.central_widget)
        self.label_23.setGeometry(QtCore.QRect(330, 370, 59, 15))
        self.label_23.setObjectName("label_23")

        self.label_24 = QtWidgets.QLabel(self.central_widget)
        self.label_24.setGeometry(QtCore.QRect(330, 400, 59, 15))
        self.label_24.setObjectName("label_24")

        self.label_10 = QtWidgets.QLabel(self.central_widget)
        self.label_10.setGeometry(QtCore.QRect(180, 310, 81, 16))
        self.label_10.setObjectName("label_10")

        self.label_13 = QtWidgets.QLabel(self.central_widget)
        self.label_13.setGeometry(QtCore.QRect(330, 310, 81, 16))
        self.label_13.setObjectName("label_13")

        self.label_16 = QtWidgets.QLabel(self.central_widget)
        self.label_16.setGeometry(QtCore.QRect(470, 310, 81, 16))
        self.label_16.setObjectName("label_16")

        self.label_19 = QtWidgets.QLabel(self.central_widget)
        self.label_19.setGeometry(QtCore.QRect(20, 430, 81, 16))
        self.label_19.setObjectName("label_19")

        self.label_22 = QtWidgets.QLabel(self.central_widget)
        self.label_22.setGeometry(QtCore.QRect(180, 430, 81, 16))
        self.label_22.setObjectName("label_22")

        self.label_25 = QtWidgets.QLabel(self.central_widget)
        self.label_25.setGeometry(QtCore.QRect(330, 430, 81, 16))
        self.label_25.setObjectName("label_25")

        self.template_tm1_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm1_start.setGeometry(QtCore.QRect(100, 240, 51, 31))
        self.template_tm1_start.setObjectName("textEdit_3")

        self.template_tm4_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm4_start.setGeometry(QtCore.QRect(550, 240, 51, 31))
        self.template_tm4_start.setObjectName("textEdit_4")

        self.template_bw1 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw1.setGeometry(QtCore.QRect(100, 300, 51, 31))
        self.template_bw1.setObjectName("textEdit_6")

        self.template_tm1_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm1_end.setGeometry(QtCore.QRect(100, 270, 51, 31))
        self.template_tm1_end.setObjectName("textEdit_7")

        self.template_bw4 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw4.setGeometry(QtCore.QRect(550, 300, 51, 31))
        self.template_bw4.setObjectName("textEdit_8")

        self.template_tm4_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm4_end.setGeometry(QtCore.QRect(550, 270, 51, 31))
        self.template_tm4_end.setObjectName("textEdit_9")

        self.template_tm2_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm2_start.setGeometry(QtCore.QRect(270, 240, 51, 31))
        self.template_tm2_start.setObjectName("textEdit_17")

        self.template_bw2 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw2.setGeometry(QtCore.QRect(270, 300, 51, 31))
        self.template_bw2.setObjectName("textEdit_18")

        self.template_tm2_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm2_end.setGeometry(QtCore.QRect(270, 270, 51, 31))
        self.template_tm2_end.setObjectName("textEdit_19")

        self.template_tm3_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm3_start.setGeometry(QtCore.QRect(410, 240, 51, 31))
        self.template_tm3_start.setObjectName("textEdit_20")

        self.template_bw3 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw3.setGeometry(QtCore.QRect(410, 300, 51, 31))
        self.template_bw3.setObjectName("textEdit_21")

        self.template_tm3_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm3_end.setGeometry(QtCore.QRect(410, 270, 51, 31))
        self.template_tm3_end.setObjectName("textEdit_22")

        self.template_tm5_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm5_start.setGeometry(QtCore.QRect(100, 360, 51, 31))
        self.template_tm5_start.setObjectName("textEdit_5")

        self.template_bw5 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw5.setGeometry(QtCore.QRect(100, 420, 51, 31))
        self.template_bw5.setObjectName("textEdit_23")

        self.template_tm5_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm5_end.setGeometry(QtCore.QRect(100, 390, 51, 31))
        self.template_tm5_end.setObjectName("textEdit_24")

        self.template_tm6_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm6_start.setGeometry(QtCore.QRect(270, 360, 51, 31))
        self.template_tm6_start.setObjectName("textEdit_25")

        self.template_bw6 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw6.setGeometry(QtCore.QRect(270, 420, 51, 31))
        self.template_bw6.setObjectName("textEdit_26")

        self.template_tm6_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm6_end.setGeometry(QtCore.QRect(270, 390, 51, 31))
        self.template_tm6_end.setObjectName("textEdit_27")

        self.template_tm7_start = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm7_start.setGeometry(QtCore.QRect(410, 360, 51, 31))
        self.template_tm7_start.setObjectName("textEdit_28")

        self.template_bw7 = QtWidgets.QTextEdit(self.central_widget)
        self.template_bw7.setGeometry(QtCore.QRect(410, 420, 51, 31))
        self.template_bw7.setObjectName("textEdit_29")

        self.template_tm7_end = QtWidgets.QTextEdit(self.central_widget)
        self.template_tm7_end.setGeometry(QtCore.QRect(410, 390, 51, 31))
        self.template_tm7_end.setObjectName("textEdit_30")

        self.label_26 = QtWidgets.QLabel(self.central_widget)
        self.label_26.setGeometry(QtCore.QRect(20, 690, 59, 15))
        self.label_26.setObjectName("label_26")

        self.label_27 = QtWidgets.QLabel(self.central_widget)
        self.label_27.setGeometry(QtCore.QRect(330, 870, 81, 16))
        self.label_27.setObjectName("label_27")

        self.target_tm5_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm5_end.setGeometry(QtCore.QRect(100, 830, 51, 31))
        self.target_tm5_end.setObjectName("textEdit_31")

        self.target_tm7_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm7_end.setGeometry(QtCore.QRect(410, 830, 51, 31))
        self.target_tm7_end.setObjectName("textEdit_32")

        self.target_tm3_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm3_start.setGeometry(QtCore.QRect(410, 680, 51, 31))
        self.target_tm3_start.setObjectName("textEdit_33")

        self.target_tm5_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm5_start.setGeometry(QtCore.QRect(100, 800, 51, 31))
        self.target_tm5_start.setObjectName("textEdit_10")

        self.target_bw1 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw1.setGeometry(QtCore.QRect(100, 740, 51, 31))
        self.target_bw1.setObjectName("textEdit_11")

        self.target_bw5 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw5.setGeometry(QtCore.QRect(100, 860, 51, 31))
        self.target_bw5.setObjectName("textEdit_34")

        self.label_28 = QtWidgets.QLabel(self.central_widget)
        self.label_28.setGeometry(QtCore.QRect(20, 870, 81, 16))
        self.label_28.setObjectName("label_28")

        self.label_29 = QtWidgets.QLabel(self.central_widget)
        self.label_29.setGeometry(QtCore.QRect(20, 750, 81, 16))
        self.label_29.setObjectName("label_29")

        self.label_30 = QtWidgets.QLabel(self.central_widget)
        self.label_30.setGeometry(QtCore.QRect(180, 810, 59, 15))
        self.label_30.setObjectName("label_30")

        self.label_31 = QtWidgets.QLabel(self.central_widget)
        self.label_31.setGeometry(QtCore.QRect(330, 690, 59, 15))
        self.label_31.setObjectName("label_31")

        self.target_bw7 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw7.setGeometry(QtCore.QRect(410, 860, 51, 31))
        self.target_bw7.setObjectName("textEdit_35")

        self.target_bw4 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw4.setGeometry(QtCore.QRect(550, 740, 51, 31))
        self.target_bw4.setObjectName("textEdit_12")

        self.label_32 = QtWidgets.QLabel(self.central_widget)
        self.label_32.setGeometry(QtCore.QRect(330, 750, 81, 16))
        self.label_32.setObjectName("label_32")

        self.label_33 = QtWidgets.QLabel(self.central_widget)
        self.label_33.setGeometry(QtCore.QRect(180, 840, 59, 15))
        self.label_33.setObjectName("label_33")

        self.label_34 = QtWidgets.QLabel(self.central_widget)
        self.label_34.setGeometry(QtCore.QRect(470, 690, 59, 15))
        self.label_34.setObjectName("label_34")

        self.target_tm7_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm7_start.setGeometry(QtCore.QRect(410, 800, 51, 31))
        self.target_tm7_start.setObjectName("textEdit_36")

        self.label_35 = QtWidgets.QLabel(self.central_widget)
        self.label_35.setGeometry(QtCore.QRect(330, 810, 59, 15))
        self.label_35.setObjectName("label_35")

        self.label_36 = QtWidgets.QLabel(self.central_widget)
        self.label_36.setGeometry(QtCore.QRect(20, 720, 59, 15))
        self.label_36.setObjectName("label_36")

        self.label_37 = QtWidgets.QLabel(self.central_widget)
        self.label_37.setGeometry(QtCore.QRect(180, 870, 81, 16))
        self.label_37.setObjectName("label_37")

        self.target_tm1_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm1_end.setGeometry(QtCore.QRect(100, 710, 51, 31))
        self.target_tm1_end.setObjectName("textEdit_13")

        self.target_bw3 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw3.setGeometry(QtCore.QRect(410, 740, 51, 31))
        self.target_bw3.setObjectName("textEdit_37")

        self.target_tm6_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm6_start.setGeometry(QtCore.QRect(270, 800, 51, 31))
        self.target_tm6_start.setObjectName("textEdit_38")

        self.target_tm4_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm4_start.setGeometry(QtCore.QRect(550, 680, 51, 31))
        self.target_tm4_start.setObjectName("textEdit_14")

        self.target_tm3_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm3_end.setGeometry(QtCore.QRect(410, 710, 51, 31))
        self.target_tm3_end.setObjectName("textEdit_39")

        self.target_tm2_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm2_end.setGeometry(QtCore.QRect(270, 710, 51, 31))
        self.target_tm2_end.setObjectName("textEdit_40")

        self.target_bw2 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw2.setGeometry(QtCore.QRect(270, 740, 51, 31))
        self.target_bw2.setObjectName("textEdit_41")

        self.label_38 = QtWidgets.QLabel(self.central_widget)
        self.label_38.setGeometry(QtCore.QRect(180, 720, 59, 15))
        self.label_38.setObjectName("label_38")

        self.target_tm1_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm1_start.setGeometry(QtCore.QRect(100, 680, 51, 31))
        self.target_tm1_start.setObjectName("textEdit_15")

        self.label_39 = QtWidgets.QLabel(self.central_widget)
        self.label_39.setGeometry(QtCore.QRect(470, 720, 59, 15))
        self.label_39.setObjectName("label_39")

        self.label_40 = QtWidgets.QLabel(self.central_widget)
        self.label_40.setGeometry(QtCore.QRect(330, 840, 59, 15))
        self.label_40.setObjectName("label_40")

        self.target_bw6 = QtWidgets.QTextEdit(self.central_widget)
        self.target_bw6.setGeometry(QtCore.QRect(270, 860, 51, 31))
        self.target_bw6.setObjectName("textEdit_42")

        self.label_41 = QtWidgets.QLabel(self.central_widget)
        self.label_41.setGeometry(QtCore.QRect(180, 690, 59, 15))
        self.label_41.setObjectName("label_41")

        self.label_42 = QtWidgets.QLabel(self.central_widget)
        self.label_42.setGeometry(QtCore.QRect(20, 840, 59, 15))
        self.label_42.setObjectName("label_42")

        self.label_43 = QtWidgets.QLabel(self.central_widget)
        self.label_43.setGeometry(QtCore.QRect(330, 720, 59, 15))
        self.label_43.setObjectName("label_43")

        self.label_44 = QtWidgets.QLabel(self.central_widget)
        self.label_44.setGeometry(QtCore.QRect(20, 810, 59, 15))
        self.label_44.setObjectName("label_44")

        self.target_tm2_start = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm2_start.setGeometry(QtCore.QRect(270, 680, 51, 31))
        self.target_tm2_start.setObjectName("textEdit_43")

        self.target_tm4_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm4_end.setGeometry(QtCore.QRect(550, 710, 51, 31))
        self.target_tm4_end.setObjectName("textEdit_16")

        self.label_45 = QtWidgets.QLabel(self.central_widget)
        self.label_45.setGeometry(QtCore.QRect(180, 750, 81, 16))
        self.label_45.setObjectName("label_45")

        self.target_tm6_end = QtWidgets.QTextEdit(self.central_widget)
        self.target_tm6_end.setGeometry(QtCore.QRect(270, 830, 51, 31))
        self.target_tm6_end.setObjectName("textEdit_44")

        self.label_46 = QtWidgets.QLabel(self.central_widget)
        self.label_46.setGeometry(QtCore.QRect(470, 750, 81, 16))
        self.label_46.setObjectName("label_46")

        self.SsdCalculator.setCentralWidget(self.central_widget)
        self.statusbar = QtWidgets.QStatusBar(self.SsdCalculator)
        self.statusbar.setObjectName("statusbar")
        self.SsdCalculator.setStatusBar(self.statusbar)

        self.translate_ui()
        QtCore.QMetaObject.connectSlotsByName(self.SsdCalculator)
        self.reset_ui()

    def translate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.SsdCalculator.setWindowTitle(_translate("SsdCalculator", "MainWindow"))
        self.label_2.setText(_translate("SsdCalculator", "SSD"))
        self.ssd_TM1.setText(_translate("SsdCalculator", "SSD-TM1"))
        self.ssd_TM2.setText(_translate("SsdCalculator", "SSD-TM2"))
        self.ssd_TM3.setText(_translate("SsdCalculator", "SSD-TM3"))
        self.ssd_TM4.setText(_translate("SsdCalculator", "SSD-TM4"))
        self.ssd_TM5.setText(_translate("SsdCalculator", "SSD-TM5"))
        self.ssd_TM6.setText(_translate("SsdCalculator", "SSD-TM6"))
        self.ssd_TM7.setText(_translate("SsdCalculator", "SSD-TM7"))

        self.calculate_button.setText(_translate("SsdCalculator", "Calculate SSD"))
        self.show_alignment_button.setText(_translate("SsdCalculator", "Alignment"))
        self.show_hydrophobicity_plot_button.setText(_translate("SsdCalculator", "Hydrophobicity plot"))
        self.show_helical_plot_button.setText(_translate("SsdCalculator", "Helical plot"))
        self.download_result_summary_button.setText(_translate("SsdCalculator", "Result summary"))
        self.home_button.setText(_translate("SsdCalculator", "Home"))
        self.example_input_button.setText(_translate("SsdCalculator", "Example input"))
        self.clear_button.setText(_translate("SsdCalculator", "Clear"))

        self.label_3.setText(_translate("SsdCalculator", "Calculate SSD for custom transmembrane(TM) definition:"))
        self.label_5.setText(_translate("SsdCalculator", "Enter Template Sequence:"))
        self.label_6.setText(_translate("SsdCalculator", "Enter Target Sequence:"))
        self.label.setText(_translate("SsdCalculator", "TM1 start:"))
        self.label_4.setText(_translate("SsdCalculator", "TM1 end:"))
        self.label_7.setText(_translate("SsdCalculator", "TM2 start:"))
        self.label_8.setText(_translate("SsdCalculator", "TM2 end:"))
        self.label_9.setText(_translate("SsdCalculator", "Position 1.50"))
        self.label_11.setText(_translate("SsdCalculator", "TM3 start:"))
        self.label_12.setText(_translate("SsdCalculator", "TM3 end:"))
        self.label_14.setText(_translate("SsdCalculator", "TM4 start:"))
        self.label_15.setText(_translate("SsdCalculator", "TM4 end:"))
        self.label_17.setText(_translate("SsdCalculator", "TM5 start:"))
        self.label_18.setText(_translate("SsdCalculator", "TM5 end:"))
        self.label_20.setText(_translate("SsdCalculator", "TM6 start:"))
        self.label_21.setText(_translate("SsdCalculator", "TM6 end:"))
        self.label_23.setText(_translate("SsdCalculator", "TM7 start:"))
        self.label_24.setText(_translate("SsdCalculator", "TM7 end:"))
        self.label_10.setText(_translate("SsdCalculator", "Position 2.50"))
        self.label_13.setText(_translate("SsdCalculator", "Position 3.50"))
        self.label_16.setText(_translate("SsdCalculator", "Position 4.50"))
        self.label_19.setText(_translate("SsdCalculator", "Position 5.50"))
        self.label_22.setText(_translate("SsdCalculator", "Position 6.50"))
        self.label_25.setText(_translate("SsdCalculator", "Position 7.50"))
        self.label_26.setText(_translate("SsdCalculator", "TM1 start:"))
        self.label_27.setText(_translate("SsdCalculator", "Position 7.50"))
        self.label_28.setText(_translate("SsdCalculator", "Position 5.50"))
        self.label_29.setText(_translate("SsdCalculator", "Position 1.50"))
        self.label_30.setText(_translate("SsdCalculator", "TM6 start:"))
        self.label_31.setText(_translate("SsdCalculator", "TM3 start:"))
        self.label_32.setText(_translate("SsdCalculator", "Position 3.50"))
        self.label_33.setText(_translate("SsdCalculator", "TM6 end:"))
        self.label_34.setText(_translate("SsdCalculator", "TM4 start:"))
        self.label_35.setText(_translate("SsdCalculator", "TM7 start:"))
        self.label_36.setText(_translate("SsdCalculator", "TM1 end:"))
        self.label_37.setText(_translate("SsdCalculator", "Position 6.50"))
        self.label_38.setText(_translate("SsdCalculator", "TM2 end:"))
        self.label_39.setText(_translate("SsdCalculator", "TM4 end:"))
        self.label_40.setText(_translate("SsdCalculator", "TM7 end:"))
        self.label_41.setText(_translate("SsdCalculator", "TM2 start:"))
        self.label_42.setText(_translate("SsdCalculator", "TM5 end:"))
        self.label_43.setText(_translate("SsdCalculator", "TM3 end:"))
        self.label_44.setText(_translate("SsdCalculator", "TM5 start:"))
        self.label_45.setText(_translate("SsdCalculator", "Position 2.50"))
        self.label_46.setText(_translate("SsdCalculator", "Position 4.50"))

    def on_text_changed(self):
        is_disabled = self.template_sequence_field.toPlainText().strip() == '' and self.target_sequence_field.toPlainText().strip() == ''
        self.calculate_button.setDisabled(is_disabled)

    def back_home(self):
        from Home import Ui_HomeWindow

        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_HomeWindow(self.window)
        self.ui.setup_ui()
        self.SsdCalculator.hide()
        self.window.setWindowTitle('Bio-GATS')
        self.window.show()

    def clear_button_handler(self):
        self.reset_ui()

    def reset_ui(self):
        self.calculate_button.setDisabled(True)
        self.show_alignment_button.setDisabled(True)
        self.show_hydrophobicity_plot_button.setDisabled(True)
        self.show_helical_plot_button.setDisabled(True)
        self.download_result_summary_button.setDisabled(True)

        self.template_sequence_field.setText('')
        self.target_sequence_field.setText('')

        self.template_tm1_start.setText('')
        self.template_tm2_start.setText('')
        self.template_tm3_start.setText('')
        self.template_tm4_start.setText('')
        self.template_tm5_start.setText('')
        self.template_tm6_start.setText('')
        self.template_tm7_start.setText('')

        self.template_tm1_end.setText('')
        self.template_tm2_end.setText('')
        self.template_tm3_end.setText('')
        self.template_tm4_end.setText('')
        self.template_tm5_end.setText('')
        self.template_tm6_end.setText('')
        self.template_tm7_end.setText('')

        self.template_bw1.setText('')
        self.template_bw2.setText('')
        self.template_bw3.setText('')
        self.template_bw4.setText('')
        self.template_bw5.setText('')
        self.template_bw6.setText('')
        self.template_bw7.setText('')

        self.target_tm1_start.setText('')
        self.target_tm2_start.setText('')
        self.target_tm3_start.setText('')
        self.target_tm4_start.setText('')
        self.target_tm5_start.setText('')
        self.target_tm6_start.setText('')
        self.target_tm7_start.setText('')

        self.target_tm1_end.setText('')
        self.target_tm2_end.setText('')
        self.target_tm3_end.setText('')
        self.target_tm4_end.setText('')
        self.target_tm5_end.setText('')
        self.target_tm6_end.setText('')
        self.target_tm7_end.setText('')

        self.target_bw1.setText('')
        self.target_bw2.setText('')
        self.target_bw3.setText('')
        self.target_bw4.setText('')
        self.target_bw5.setText('')
        self.target_bw6.setText('')
        self.target_bw7.setText('')

    def example_button_handler(self):
        self.template_sequence_field.setText(
            'MEEPGAQCAPPPPAGSETWVPQANLSSAPSQNCSAKDYIYQDSISLPWKVLLVMLLALITLATTLSNAFVIATVYRTRKLHTPANYLIASLAVTDLLVSILVMPISTMYTVTGRWTLGQVVCDFWLSSDITCCTASILHLCVIALDRYWAITDAVEYSAKRTPKRAAVMIALVWVFSISISLPPFFWRQAKAEEEVSECVVNTDHILYTVYSTVGAFYFPTLLLIALYGRIYVEARSRILKQTPNRTGKRLTRAQLITDSPGSTSSVTSINSRVPDVPSESGSPVYVNQVKVRVSDALLEKKKLMAARERKATKTLGIILGAFIVCWLPFFIISLVMPICKDACWFHLAIFDFFTWLGYLNSLINPIIYTMSNEDFKQAFHKLIRFKCTS')
        self.target_sequence_field.setText(
            'MLRNNLGNSSDSKNEDGSVFSQTEHNIVATYLIMAGMISIISNIIVLGIFIKYKELRTPTNAIIINLAVTDIGVSSIGYPMSAASDLYGSWKFGYAGCQVYAGLNIFFGMASIGLLTVVAVDRYLTICLPDVGRRMTTNTYIGLILGAWINGLFWALMPIIGWASYAPDPTGATCTINWRKNDRSFVSYTMTVIAINFIVPLTVMFYCYYHVTLSIKHHTTSDCTESLNRDWSDQIDVTKMSVIMICMFLVAWSPYSIVCLWASFGDPKKIPPPMAIIAPLFAKSSTFYNPCIYVVANKKFRRAMLAMFKCQTHQTMPVTSILPMDVSQNPLASGRI')

        self.template_tm1_start.setText('46')
        self.template_tm2_start.setText('83')
        self.template_tm3_start.setText('119')
        self.template_tm4_start.setText('163')
        self.template_tm5_start.setText('206')
        self.template_tm6_start.setText('311')
        self.template_tm7_start.setText('348')

        self.template_tm1_end.setText('76')
        self.template_tm2_end.setText('112')
        self.template_tm3_end.setText('152')
        self.template_tm4_end.setText('185')
        self.template_tm5_end.setText('238')
        self.template_tm6_end.setText('338')
        self.template_tm7_end.setText('372')

        self.template_bw1.setText('67')
        self.template_bw2.setText('95')
        self.template_bw3.setText('147')
        self.template_bw4.setText('174')
        self.template_bw5.setText('220')
        self.template_bw6.setText('329')
        self.template_bw7.setText('366')

        self.target_tm1_start.setText('23')
        self.target_tm2_start.setText('59')
        self.target_tm3_start.setText('95')
        self.target_tm4_start.setText('138')
        self.target_tm5_start.setText('185')
        self.target_tm6_start.setText('233')
        self.target_tm7_start.setText('271')

        self.target_tm1_end.setText('52')
        self.target_tm2_end.setText('87')
        self.target_tm3_end.setText('128')
        self.target_tm4_end.setText('162')
        self.target_tm5_end.setText('218')
        self.target_tm6_end.setText('265')
        self.target_tm7_end.setText('297')

        self.target_bw1.setText('43')
        self.target_bw2.setText('71')
        self.target_bw3.setText('123')
        self.target_bw4.setText('149')
        self.target_bw5.setText('201')
        self.target_bw6.setText('255')
        self.target_bw7.setText('291')

    def validate_input(self):
        template_sequence_text = re.sub('\\s', '', self.template_sequence_field.toPlainText())
        target_sequence_text = re.sub('\\s', '', self.target_sequence_field.toPlainText())

        # check if sequence is empty
        msg = QtWidgets.QMessageBox()
        if not template_sequence_text:
            QtWidgets.QMessageBox.about(msg, "Warning", "Please enter a valid template sequence")
            return False

        # verify protein sequence
        elif not target_sequence_text:
            QtWidgets.QMessageBox.about(msg, "Warning", "Please enter a valid target sequence")
            return False

        for residue in re.findall('[a-zA-Z]', template_sequence_text):
            if residue not in Helper.valid_residues:
                QtWidgets.QMessageBox.about(msg, "Warning", "Please enter a valid GPCR sequence")
                return False

        positions = [
            self.template_tm1_start.toPlainText(),
            self.template_tm2_start.toPlainText(),
            self.template_tm3_start.toPlainText(),
            self.template_tm4_start.toPlainText(),
            self.template_tm5_start.toPlainText(),
            self.template_tm6_start.toPlainText(),
            self.template_tm7_start.toPlainText(),

            self.template_tm1_end.toPlainText(),
            self.template_tm2_end.toPlainText(),
            self.template_tm3_end.toPlainText(),
            self.template_tm4_end.toPlainText(),
            self.template_tm5_end.toPlainText(),
            self.template_tm6_end.toPlainText(),
            self.template_tm7_end.toPlainText(),

            self.template_bw1.toPlainText(),
            self.template_bw2.toPlainText(),
            self.template_bw3.toPlainText(),
            self.template_bw4.toPlainText(),
            self.template_bw5.toPlainText(),
            self.template_bw6.toPlainText(),
            self.template_bw7.toPlainText(),

            self.target_tm1_start.toPlainText(),
            self.target_tm2_start.toPlainText(),
            self.target_tm3_start.toPlainText(),
            self.target_tm4_start.toPlainText(),
            self.target_tm5_start.toPlainText(),
            self.target_tm6_start.toPlainText(),
            self.target_tm7_start.toPlainText(),

            self.target_tm1_end.toPlainText(),
            self.target_tm2_end.toPlainText(),
            self.target_tm3_end.toPlainText(),
            self.target_tm4_end.toPlainText(),
            self.target_tm5_end.toPlainText(),
            self.target_tm6_end.toPlainText(),
            self.target_tm7_end.toPlainText(),

            self.target_bw1.toPlainText(),
            self.target_bw2.toPlainText(),
            self.target_bw3.toPlainText(),
            self.target_bw4.toPlainText(),
            self.target_bw5.toPlainText(),
            self.target_bw6.toPlainText(),
            self.target_bw7.toPlainText(),
        ]

        # check for any character other than digits
        for position in positions:
            current_position = position.strip()
            if not current_position or not re.match('[0-9]', current_position):
                QtWidgets.QMessageBox.about(msg, "Warning", "Please enter a valid positions")
                return False

        return True

    def calculate(self):
        if not self.validate_input():
            return

        self.show_alignment_button.setDisabled(False)
        self.show_hydrophobicity_plot_button.setDisabled(False)
        self.show_helical_plot_button.setDisabled(False)
        self.download_result_summary_button.setDisabled(False)

        self.target_sequence = self.target_sequence_field.toPlainText().strip()  # getting target sequence
        self.template_sequence = self.template_sequence_field.toPlainText().strip()  # getting template sequence

        self.split_helix(self.template_sequence, type='template', numbers=True)
        self.alignment = self.align()

        self.target_number = [
            (int(self.target_tm1_start.toPlainText()), int(self.target_tm1_end.toPlainText())),
            (int(self.target_tm2_start.toPlainText()), int(self.target_tm2_end.toPlainText())),
            (int(self.target_tm3_start.toPlainText()), int(self.target_tm3_end.toPlainText())),
            (int(self.target_tm4_start.toPlainText()), int(self.target_tm4_end.toPlainText())),
            (int(self.target_tm5_start.toPlainText()), int(self.target_tm5_end.toPlainText())),
            (int(self.target_tm6_start.toPlainText()), int(self.target_tm6_end.toPlainText())),
            (int(self.target_tm7_start.toPlainText()), int(self.target_tm7_end.toPlainText())),
        ]
        self.template_number = [
            (int(self.template_tm1_start.toPlainText()), int(self.template_tm1_end.toPlainText())),
            (int(self.template_tm2_start.toPlainText()), int(self.template_tm2_end.toPlainText())),
            (int(self.template_tm3_start.toPlainText()), int(self.template_tm3_end.toPlainText())),
            (int(self.template_tm4_start.toPlainText()), int(self.template_tm4_end.toPlainText())),
            (int(self.template_tm5_start.toPlainText()), int(self.template_tm5_end.toPlainText())),
            (int(self.template_tm6_start.toPlainText()), int(self.template_tm6_end.toPlainText())),
            (int(self.template_tm7_start.toPlainText()), int(self.template_tm7_end.toPlainText())),
        ]

        ssd_tm = self.ssd()
        self.ssd_TM1.setText('TM1: ' + str(ssd_tm[0]))  # SSD for TM1
        self.ssd_TM2.setText('TM2: ' + str(ssd_tm[1]))
        self.ssd_TM3.setText('TM3: ' + str(ssd_tm[2]))
        self.ssd_TM4.setText('TM4: ' + str(ssd_tm[3]))
        self.ssd_TM5.setText('TM5: ' + str(ssd_tm[4]))
        self.ssd_TM6.setText('TM6: ' + str(ssd_tm[5]))
        self.ssd_TM7.setText('TM7: ' + str(ssd_tm[6]))

    def split_helix(self, id, type, numbers):
        prot = [[None for x in range(7)], [None for y in range(7)]]
        numb = [[None for x in range(7)], [None for y in range(7)]]
        seq = ''
        positions = []

        targets = [
            {'start': self.target_tm1_start.toPlainText(), 'end': self.target_tm1_end.toPlainText(), 'bw': self.target_bw1.toPlainText()},
            {'start': self.target_tm2_start.toPlainText(), 'end': self.target_tm2_end.toPlainText(), 'bw': self.target_bw2.toPlainText()},
            {'start': self.target_tm3_start.toPlainText(), 'end': self.target_tm3_end.toPlainText(), 'bw': self.target_bw3.toPlainText()},
            {'start': self.target_tm4_start.toPlainText(), 'end': self.target_tm4_end.toPlainText(), 'bw': self.target_bw4.toPlainText()},
            {'start': self.target_tm5_start.toPlainText(), 'end': self.target_tm5_end.toPlainText(), 'bw': self.target_bw5.toPlainText()},
            {'start': self.target_tm6_start.toPlainText(), 'end': self.target_tm6_end.toPlainText(), 'bw': self.target_bw6.toPlainText()},
            {'start': self.target_tm7_start.toPlainText(), 'end': self.target_tm7_end.toPlainText(), 'bw': self.target_bw7.toPlainText()},
        ]
        templates = [
            {'start': self.template_tm1_start.toPlainText(), 'end': self.template_tm1_end.toPlainText(), 'bw': self.template_bw1.toPlainText()},
            {'start': self.template_tm2_start.toPlainText(), 'end': self.template_tm2_end.toPlainText(), 'bw': self.template_bw2.toPlainText()},
            {'start': self.template_tm3_start.toPlainText(), 'end': self.template_tm3_end.toPlainText(), 'bw': self.template_bw3.toPlainText()},
            {'start': self.template_tm4_start.toPlainText(), 'end': self.template_tm4_end.toPlainText(), 'bw': self.template_bw4.toPlainText()},
            {'start': self.template_tm5_start.toPlainText(), 'end': self.template_tm5_end.toPlainText(), 'bw': self.template_bw5.toPlainText()},
            {'start': self.template_tm6_start.toPlainText(), 'end': self.template_tm6_end.toPlainText(), 'bw': self.template_bw6.toPlainText()},
            {'start': self.template_tm7_start.toPlainText(), 'end': self.template_tm7_end.toPlainText(), 'bw': self.template_bw7.toPlainText()},
        ]

        if type == 'template':
            seq = self.template_sequence_field.toPlainText()
            positions = templates
        elif type == 'target':
            seq = self.target_sequence_field.toPlainText()
            positions = targets

        for i in range(1, 8):
            start = positions[i - 1]['start']  # template_tm1_start or target_tm1_start
            end = positions[i - 1]['end']  # template_tm1_end or target_tm1_end
            bw = positions[i - 1]['bw']  # template_bw or target_bw

            prot[0][i - 1] = seq[(int(start) - 1):int(end)]
            prot[1][i - 1] = int(bw) - int(start)
            numb[0][i - 1] = [int(start), int(end)]
            numb[1][i - 1] = int(bw)

        if numbers == False:
            return (prot)
        if numbers == True:
            return (numb)

    def align(self):
        self.template = self.split_helix(self.template_sequence_field.toPlainText(), 'template', False)
        self.target = self.split_helix(self.target_sequence_field.toPlainText(), 'target', False)

        align = [[None for x in range(7)], [None for y in range(7)]]

        for i in range(7):
            if self.template[1][i] > self.target[1][i]:
                align[0][i] = self.template[0][i]
                align[1][i] = ''.join(['-'] * (self.template[1][i] - self.target[1][i])) + self.target[0][i]
            elif self.template[1][i] < self.target[1][i]:
                align[0][i] = ''.join(['-'] * (self.target[1][i] - self.template[1][i])) + self.template[0][i]
                align[1][i] = self.target[0][i]
            else:
                align[0][i] = self.template[0][i]
                align[1][i] = self.target[0][i]
            if len(align[0][i]) > len(align[1][i]):
                align[1][i] = align[1][i] + ''.join(['-'] * (len(align[0][i]) - len(align[1][i])))
            elif len(align[1][i]) > len(align[0][i]):
                align[0][i] = align[0][i] + ''.join(['-'] * (len(align[1][i]) - len(align[0][i])))

        return align

    def ssd(self):
        template = self.template_sequence_field.toPlainText()
        target = self.target_sequence_field.toPlainText()
        windowl = 11
        hyd = [None, None]
        hyd[0] = [Helper.hydscale[res] for res in template]
        hyd[1] = [Helper.hydscale[res] for res in target]
        lens = [len(template), len(target)]
        hydr = [[1] * int(windowl / 2) for i in range(2)]
        for k in range(2):
            for i in range(int(windowl / 2), lens[k] - int(windowl / 2)):
                sumb = 0
                for j in range(-int(windowl / 2), int(windowl / 2) + 1):
                    sumb += hyd[k][i + j]
                avg = sumb / windowl
                hydr[k].append(avg)
        for i in range(2):
            hydr[i] += [1] * int(windowl / 2)
        templist = list(template)
        targlist = list(target)
        length = len(templist)
        targalign = ['-'] * (length)
        tempalign = templist
        tempvals = self.split_helix(template, type='template', numbers=True)
        targvals = self.split_helix(target, type='target', numbers=True)
        temphelix = tempvals[0]
        targhelix = targvals[0]
        tempBW = tempvals[1]
        targBW = targvals[1]
        self.name = 'template,target'
        hydiff = []
        self.hydrh = [[[] for x in range(2)] for y in range(7)]
        self.ress = [[] for y in range(7)]
        perresssd = []
        for i in range(7):
            self.summ = [0] * 7
            for j in range(int(targhelix[i][0]) - 1, int(targhelix[i][1])):
                targalign[j + tempBW[i] - targBW[i]] = targlist[j]
            for j in range(int(temphelix[i][0]) - 1, int(temphelix[i][1])):
                self.hydrh[i][0].append(hydr[0][j])
                self.hydrh[i][1].append(hydr[1][targBW[i] - tempBW[i] + j])
                self.summ[i] += ((hydr[1][targBW[i] - tempBW[i] + j]) - (hydr[0][j])) ** 2
            # resno = (tempBW[i] - targBW[i] + targhelix[i][0]) - temphelix[i][0]
            self.ress[i] = [x for x in range(int(temphelix[i][0]), int(temphelix[i][1] + 1))]
            self.value[i] = self.summ[i] / (temphelix[i][1] - temphelix[i][0] + 1)
            hydiff.append(round(self.summ[i], 3))
            perresssd.append(round(self.value[i], 3))

        return (perresssd)

    def show_alignment_click_handler(self):
        print(self.template_sequence)
        print(self.target_sequence)
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Alignment(self.window, self.alignment, 'Template', 'Target', self.template_sequence, self.target_sequence, self.template_number, self.target_number)
        self.ui.setup_ui()
        self.window.setWindowTitle('Alignment - Bio-GATS')
        self.window.show()

    def show_hydrophobicity_plot(self):
        Helper.show_hydrophobicity_plot(self.ress, self.hydrh, self.summ, self.value, '', '', self.name, download=False)

    def show_helical_plot(self):
        Helper.show_helical_plot(self.template, self.target, '', '', self.name, download=False)

    def download_result_summary(self):
        hydrophobicity_plot_filenames = Helper.show_hydrophobicity_plot(self.ress, self.hydrh, self.summ, self.value, '', '', self.name, download=True)
        helical_plot_filenames = Helper.show_helical_plot(self.template, self.target, '', '', self.name, download=True)
        Helper.generate_result_summary(self.alignment, 'Template', 'Target', self.template_sequence, self.target_sequence, self.template_number, self.target_number, hydrophobicity_plot_filenames, helical_plot_filenames)
